### ISSUE TITLE
Sorry for the (extremely) late reply.

### ISSUE THREAD

**Issue by oyeadegboye** [grantbrown/ABSEIR#7] opened 2020-02-08 10:55 UTC
Sorry for the (extremely) late reply. 

This isn't a feature I've been using much, but I've finally gotten around to reintroducing/testing it. 

Check out the following example: [based on the 1995 Kikwit data](https://gist.githubusercontent.com/grantbrown/73c1db1beb6c789f16dfd2f2b4c4b535/raw/e175eec11582a07029a32fc328e953a9150de17b/KikwitPredictionExample.R)

The basic idea is to leave the future data as NA's in the data model, but still provide any temporal co-variate information required to make projections. The way this is coded, it shouldn't have a huge cost over running the models without keeping track of compartments, except with a large number of spatial locations.

_Originally posted by @grantbrown in https://github.com/grantbrown/ABSEIR/issues/3#issuecomment-273838581_

**Comment by oyeadegboye** [comment] 2020-02-08 11:03
Hi Grant,
I ran the example provided on R 3.6.2 using ABSEIR_1.2.4 , however R crashed each time.
Thanks

**Comment by grantbrown** [comment] 2020-02-09 02:26
Are you on Windows? I've also recently had trouble and am currently investigating if changes in R or Rtools on Windows may be related.

**Comment by oyeadegboye** [comment] 2020-02-09 02:34
Yes, I am on Windows. Do I need to downgrade?

**Comment by grantbrown** [comment] 2020-02-09 17:22
No, I'm going to try and investigate - I don't want to recommend anything until I figure out where the issue is definitely coming from.

**Comment by grantbrown** [comment] 2020-02-18 03:41
Sorry for the delays, I've had limited time to investigate this. I've confirmed that when the code is compiled in single-threaded mode, things seem to work as expected. I've also done some analysis with Valgrind and haven't seen any obvious problems. My working hypothesis is that there's something wrong with the threading code on Windows machines, but I'm not sure exactly what's causing it. 

My recommendation for now is to download a copy of the L1 branch from this GitHub repository, and then install it locally. Before you install, replace line 2 from the /src/Makevars file with:

    PKG_CPPFLAGS= -DSPATIALSEIR_SINGLETHREAD -Wno-ignored-attributes -pthread -I./include

**Comment by grantbrown** [comment] 2020-02-18 03:43
Oops, didn't mean to close. Anyway, you can install the package by running

    R CMD INSTALL ABSEIR

in the directory where the ABSEIR folder is located (assuming you have R on your system path). Alternatively, you can use the devtools::install function to install it from within R. Let me know if you need any additional info on those steps, sorry for the inconvenience.

**Comment by oyeadegboye** [comment] 2020-02-18 07:19
Thank you so much, I am trying it but I could not install the new ABSEIR directly in R. Could you please break down the steps a little further? Thanks

**Comment by grantbrown** [comment] 2020-02-19 19:55
1. Download a copy of this repository directly by clicking the "Clone or Download" button and selecting a zip file
2. Extract the zip file to a folder (like Documents)
3. Go into the "src" folder (ABSEIR/src), and edit the line which starts with "PKG_CPPFLAGS" to read as follows, using a plain text editor like notepad or notepad++:

    PKG_CPPFLAGS= -DSPATIALSEIR_SINGLETHREAD -Wno-ignored-attributes -pthread -I./include

4. Load an R session, install the "devtools" package, and run:

    library(devtools)
    devtools::install("/path/to/ABSEIR/folder/goes/here")

of course, substituting your path for the one given above. 

Does that help?

**Comment by oyeadegboye** [comment] 2020-02-19 23:21
Thank you it works now, however I will need to run it on a computer or cloud with multiple cores due to the following errors:
Initializing Model Components
...Building data model
...Building distance model
...Building exposure model
...Building initial value container
...Building reinfection model
...Building sampling control model
Errors generated:
<Rcpp::exception in new_CppObject_xp(fields$.module, fields$.pointer, ...): Error: multiple cores requested for ABSEIR compiled in single thread mode>
Error in value[[3L]](cond) : Aborting
Timing stopped at: 0 0 0

**Comment by grantbrown** [comment] 2020-02-20 14:23
When compiled with this option, the number of cores specified in the sampling control object must be set to 1. Alternatively, you could use the L1 branch compiled normally on a Linux machine until we figure out why Windows machines are having trouble with the threading code.

**Comment by oyeadegboye** [comment] 2020-02-20 22:51
Thanks it worked when n_cores=1. Thank you

**Comment by grantbrown** [comment] 2020-02-28 03:44
I believe the latest version on the master branch should solve your issue, allowing multiple cores to be used again. Apologies for the slow fix - closing for now, but please let me know if you continue to have issues.

**Closed as completed by grantbrown** 2020-02-28 03:44 UTC
