### ISSUE TITLE
Need help with 2 errors encountered, when creating Data Model & running overall model

### ISSUE THREAD

**Issue by nkniep888** [grantbrown/ABSEIR#10] opened 2020-07-28 15:37 UTC
Error 1: I'm encountering the error, "Warning message: In if (class(Y) != "matrix") { :  the condition has length > 1 and only the first element will be used" when trying to assign my matrix to the Data Model. When I try class(mymatrix) to check that my matrix is truly a matrix, I get back "[1] "matrix" "array"." I'm not sure where I am going wrong here.

Error 2: When I run the overall model I get an error back that says, "Exposure model and data model imply different number of time points:126, 2." I'm a little lost on this one as well. Obviously there is an issue with the Data Model in general, but my Exposure Model has two covariates that do not change over time so I think there should only be one time point for the exposure matrix? Since my Data Model is supposed to have 126 time points, I'm not sure how to rectify this.

I'm still pretty new to using this package so please forgive me if these questions are poorly worded or illogical! Thank you!

**Comment by grantbrown** [comment] 2020-07-29 21:27
Hi @nkniep888, 

The first issue can be safely ignored - it's caused by a very recent change in R's default behaviour. Starting with R version 4.0, matrices have two classes ([more on S3 classes here](http://adv-r.had.co.nz/OO-essentials.html)). Instead of being just class "matrix", which is a character vecter of length one, they're now class c("matrix", "array"), so old checks for whether the class of Y was equal to matrix throw that warning. The first element of the comparison is still true though, so everything should work as intended. This warning will be fixed in the next version.  

The second issue is a more fundamental one. There's no separate syntax for specifying time-varying or non-time varying covariates. Instead, we leave it up to the user to specify a type of [design matrix](https://en.wikipedia.org/wiki/Design_matrix). For each location $i$ under study, we specify a matrix $X^(i)$ which has a number of rows equal to the number of time points, and a number of columns equal to the number of terms in the design matrix (covariates, indices, etc). Then, we concatenate these matrices row-wise (that is, we basically stack them up using rbind). 

For example, if I want to fit a model with three locations and four time points which allows a separate intercept for each location, one way to do so would be:

    1    0    0
    1    0    0
    1    0    0
    1    0    0
    0    1    0
    0    1    0
    0    1    0
    0    1    0
    0    0    1
    0    0    1
    0    0    1
    0    0    1

If there was a non-time-varying covariate for each location as well, that would form an additional column:
   
    1    0    0    2.9
    1    0    0    2.9
    1    0    0    2.9
    1    0    0    2.9
    0    1    0    72.83
    0    1    0    72.83
    0    1    0    72.83
    0    1    0    72.83
    0    0    1    21.2
    0    0    1    21.2
    0    0    1    21.2
    0    0    1    21.2


The same thing would be true for time-varying covariates as well, except that they'd change between rows within each location block. 

Hope that helps - it's non-standard for sure, but coming up with a simple and yet highly general way to specify these models is fairly challenging. 

Edit: fixed the matrices to match the description

**Closed as completed by grantbrown** 2020-07-29 21:27 UTC
